default:
	gcc -o prog main.c stringWrap.c input.c listArrayList.c listElem.c mapArrayList.c mapElem.c earthquake.c earthquakeUtils.c countryStatistics.c countryStatisticsUtils.c countryLocations.c date.c time.c histogram.c -lm
debug:
	gcc -g -o prog main.c stringWrap.c input.c listArrayList.c listElem.c mapArrayList.c mapElem.c earthquake.c earthquakeUtils.c countryStatistics.c countryStatisticsUtils.c countryLocations.c date.c time.c histogram.c -lm
clean:
	rm -f prog